#include "register_script.hpp"
#include <input/key_code.hpp>
namespace sinen {
void register_keycode(sol::state &v) {
  v["keyA"] = (int)key_code::A;
  v["keyB"] = (int)key_code::B;
  v["keyC"] = (int)key_code::C;
  v["keyD"] = (int)key_code::D;
  v["keyE"] = (int)key_code::E;
  v["keyF"] = (int)key_code::F;
  v["keyG"] = (int)key_code::G;
  v["keyH"] = (int)key_code::H;
  v["keyI"] = (int)key_code::I;
  v["keyJ"] = (int)key_code::J;
  v["keyK"] = (int)key_code::K;
  v["keyL"] = (int)key_code::L;
  v["keyM"] = (int)key_code::M;
  v["keyN"] = (int)key_code::N;
  v["keyO"] = (int)key_code::O;
  v["keyP"] = (int)key_code::P;
  v["keyQ"] = (int)key_code::Q;
  v["keyR"] = (int)key_code::R;
  v["keyS"] = (int)key_code::S;
  v["keyT"] = (int)key_code::T;
  v["keyU"] = (int)key_code::U;
  v["keyV"] = (int)key_code::V;
  v["keyW"] = (int)key_code::W;
  v["keyX"] = (int)key_code::X;
  v["keyY"] = (int)key_code::Y;
  v["keyZ"] = (int)key_code::Z;
  v["key0"] = (int)key_code::Key0;
  v["key1"] = (int)key_code::Key1;
  v["key2"] = (int)key_code::Key2;
  v["key3"] = (int)key_code::Key3;
  v["key4"] = (int)key_code::Key4;
  v["key5"] = (int)key_code::Key5;
  v["key6"] = (int)key_code::Key6;
  v["key7"] = (int)key_code::Key7;
  v["key8"] = (int)key_code::Key8;
  v["key9"] = (int)key_code::Key9;
  v["keyF1"] = (int)key_code::F1;
  v["keyF2"] = (int)key_code::F2;
  v["keyF3"] = (int)key_code::F3;
  v["keyF4"] = (int)key_code::F4;
  v["keyF5"] = (int)key_code::F5;
  v["keyF6"] = (int)key_code::F6;
  v["keyF7"] = (int)key_code::F7;
  v["keyF8"] = (int)key_code::F8;
  v["keyF9"] = (int)key_code::F9;
  v["keyF10"] = (int)key_code::F10;
  v["keyF11"] = (int)key_code::F11;
  v["keyF12"] = (int)key_code::F12;
  v["keyUP"] = (int)key_code::UP;
  v["keyDOWN"] = (int)key_code::DOWN;
  v["keyLEFT"] = (int)key_code::LEFT;
  v["keyRIGHT"] = (int)key_code::RIGHT;
  v["keyESCAPE"] = (int)key_code::ESCAPE;
  v["keySPACE"] = (int)key_code::SPACE;
  v["keyENTER"] = (int)key_code::RETURN;
  v["keyBACKSPACE"] = (int)key_code::BACKSPACE;
  v["keyTAB"] = (int)key_code::TAB;
  v["keyLSHIFT"] = (int)key_code::LSHIFT;
  v["keyRSHIFT"] = (int)key_code::RSHIFT;
  v["keyLCTRL"] = (int)key_code::LCTRL;
  v["keyRCTRL"] = (int)key_code::RCTRL;
  v["keyALT"] = (int)key_code::ALTERASE;
  v["keyLCTRL"] = (int)key_code::LCTRL;
  v["keyRCTRL"] = (int)key_code::RCTRL;
}

} // namespace sinen
