option(BUILD_SHARED_LIBS OFF)
set(SDL_SHARED ${BUILD_SHARED_LIBS})
set(SDL_STATIC NOT ${BUILD_SHARED_LIBS})
set(SDLMIXER_GME OFF)
set(SDLMIXER_MOD OFF)
set(SDL3_INCLUDE_PATHS
        ${SINEN_SOURCE_DIR}/libs/SDL/include
        ${SINEN_SOURCE_DIR}/libs/SDL_image/include
)
set(ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT OFF)
set(PARANOIXA_BUILD_SDL3 OFF)

if (WIN32)
    set(SLANG_EMBED_CORE_MODULE_SOURCE OFF)
    set(SLANG_ENABLE_EXAMPLES OFF)
    set(SLANG_ENABLE_TESTS OFF)
    set(SLANG_ENABLE_REPLAYER OFF)
    set(SLANG_ENABLE_SLANGC OFF)
    set(SLANG_ENABLE_SLANGD OFF)
    set(SLANG_ENABLE_SLANGI OFF)
    set(SLANG_ENABLE_GFX OFF)
    set(SLANG_RHI_ENABLE OFF)
    set(SLANG_LIB_TYPE STATIC)
endif ()

set(USE_STATIC_MSVC_RUNTIME_LIBRARY OFF) 