set(SINEN_INCLUDE_DIRS
        ${SINEN_SOURCE_DIR}
        ${SINEN_SOURCE_DIR}/include
        ${SINEN_SOURCE_DIR}/include/sinen
        ${SINEN_SOURCE_DIR}/libs/paranoixa/library/imgui
        ${SINEN_SOURCE_DIR}/libs/paranoixa/library/imgui/backends
        ${SINEN_SOURCE_DIR}/libs/rapidjson/include
        ${SINEN_SOURCE_DIR}/libs/SDL/include
        ${SINEN_SOURCE_DIR}/libs/miniaudio
        ${SINEN_SOURCE_DIR}/libs/paranoixa/include
        ${SINEN_SOURCE_DIR}/libs/paranoixa/source/imgui_backend
        ${SINEN_SOURCE_DIR}/src/script/include
        ${SINEN_SOURCE_DIR}/src/rt_shader_compiler/include
        ${SINEN_SOURCE_DIR}/libs/assimp/include
        ${SINEN_SOURCE_DIR}/libs/glm
        ${SINEN_SOURCE_DIR}/libs/SDL/include
        ${SINEN_SOURCE_DIR}/libs/zep/include
        ${SINEN_SOURCE_DIR}/libs/sol2/include
        ${SINEN_SOURCE_DIR}/libs/stb
        ${SINEN_SOURCE_DIR}/libs/slang/include
        ${SINEN_SOURCE_DIR}/libs/JoltPhysics
        ${SINEN_SOURCE_DIR}/libs/lua
        ${SINEN_SOURCE_DIR}/libs/tinyexr
        ${SINEN_SOURCE_DIR}/libs/tinyexr/deps/miniz
)
