option(BUILD_SHARED_LIBS OFF)
set(SDL_SHARED ${BUILD_SHARED_LIBS})
set(SDL_STATIC NOT ${BUILD_SHARED_LIBS})
set(SDL3_INCLUDE_PATHS ${SINEN_SOURCE_DIR}/libs/SDL/include)
set(ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT OFF)
set(ASSIMP_WARNINGS_AS_ERRORS OFF CACHE BOOL
    "Do not treat warnings from the Assimp dependency as errors" FORCE)
if(EMSCRIPTEN)
  set(ASSIMP_BUILD_ZLIB ON CACHE BOOL "Build assimp's bundled zlib" FORCE)
endif()

set(ENABLE_ALL_WARNINGS OFF)

set(USE_STATIC_MSVC_RUNTIME_LIBRARY OFF)

set(WEBGPU_LINK_TYPE SHARED CACHE STRING "Native WebGPU link type")

set(MSDFGEN_CORE_ONLY ON)
set(MSDFGEN_BUILD_STANDALONE OFF)
set(MSDFGEN_USE_VCPKG OFF)
set(MSDFGEN_USE_CPP11 ON)
set(MSDFGEN_USE_SKIA OFF)
set(MSDFGEN_DYNAMIC_RUNTIME ON)

set(LUAU_BUILD_TESTS OFF CACHE BOOL "Build Luau tests" FORCE)
set(LUAU_BUILD_CLI OFF CACHE BOOL "Build Luau CLI tools" FORCE)
set(LUAU_EXTERN_C OFF CACHE BOOL "Use extern C for Luau APIs" FORCE)
set(LUAU_STATIC_CRT OFF CACHE BOOL "Use static CRT for Luau" FORCE)
set(LUAU_ROOT ${SINEN_SOURCE_DIR}/libs/luau)

set(CPP_DAP_ROOT ${SINEN_SOURCE_DIR}/libs/cppdap)
